### ISSUE TITLE
Make file reader able to ignore spaces

### ISSUE THREAD

**Issue by Mochatitan** [Mochatitan/savefiletest#6]
currently, the method for reading the file requires the format of 'exp:20' and would bug out the integer if it was 'exp: 20'. This isnt a game changing bug, and also good for beginners, as it only requires basic knowledge of the String class.

**Comment by Divyaganeshwala** [comment]
Does the load funtion in Tracker.java file need to be updated? If so, can I work on this issue?

**Comment by Mochatitan** [comment]
yes, around line 134-136 is when the line gets translated into the seperate parts, that is where you could add something to check and fix if there is a space. thank you

**Comment by Divyaganeshwala** [comment]
Sure, thanks! This would be my first contribution. I've created a PR.
